# Generated by Django 4.0.5 on 2022-07-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.AddField(
            model_name='product',
            name='available_quantity',
            field=models.IntegerField(default=0, help_text='Enter the Available Quantity Greater than 0', verbose_name='Quantity Available'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.SmallIntegerField(choices=[(1, 'Comming Soon'), (2, 'Available'), (3, 'Out of Stock')], default=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
