# Generated by Django 4.0.6 on 2022-08-04 19:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catlevel',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)], verbose_name='Category Level'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Parent Category'),
        ),
    ]
