# Generated by Django 4.0.6 on 2022-09-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productvarient'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_varient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
