# Generated by Django 4.0.6 on 2022-10-22 00:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catlevel',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)], verbose_name='Category Level'),
        ),
    ]
