# Generated by Django 4.1.2 on 2022-10-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_product_discount_active_product_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Discount Percentage'),
        ),
    ]
