# Generated by Django 4.0.5 on 2022-07-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_buyer_address_buyer_city_buyer_complete_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='complete_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
