# Generated by Django 4.0.2 on 2022-02-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='buyer',
        ),
    ]
