# Generated by Django 4.0.2 on 2022-02-23 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
        ('order', '0003_remove_orderitem_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='buyer.buyer'),
            preserve_default=False,
        ),
    ]
