# Generated by Django 4.0.2 on 2022-02-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderitem_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='buyer',
            field=models.CharField(max_length=255),
        ),
    ]
