# Generated by Django 4.0.5 on 2022-07-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderstatusenum_remove_order_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatusEnum',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.SmallIntegerField(choices=[(1, 'Varified'), (2, 'Not Varified'), (3, 'Delivered')], default=2),
        ),
    ]
