# Generated by Django 4.0.5 on 2022-07-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_paid_slip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_slip',
            field=models.FileField(blank=True, upload_to='slips/'),
        ),
    ]
