# Generated by Django 4.0.6 on 2022-09-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_order_paid_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_varient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
